# Project information
site_name: 'Manual PDV Info'
site_description: 'Tudo sob Controle'
site_author: 'Movin`'
site_url: 'http://pdvinfo.com.br'

nav:
  - Início: index.md
  - Primeiros Passos: primeiros-passos.md
  - Tempo Real: temporeal.md
  - Gerenciamento:  
    - Roteiro: gerenciamento/roteiro.md
    - SKU: gerenciamento/sku.md
    - Carteira: gerenciamento/carteira.md
    - Grupos: gerenciamento/grupos.md
    - Cadastro de PDV: gerenciamento/pdv.md
  - Importação em Lotes:
    - Geral: lotes/geral.md
    - Roteiro: lotes/roteiro.md
    - Pesquisa: lotes/pesquisa.md
    - SKU: lotes/sku.md
    - Carteira: lotes/carteira.md
  - Relatórios:
    - Geral: relatorios/geral.md
    - Relatório de Colaboradores: relatorios/colaboradores.md
    - Relatório de PDV/Local: relatorios/pdvlocal.md
    - Relatório de Pesquisas: relatorios/pesquisas.md
    - Relatório de Roteiros: relatorios/roteiros.md
  - Dúvidas Frequentes: 
    - Inicio: duvidas.md

     
  


theme:
  
  name: null
  custom_dir: material-custom/material
  language: pt
  font:
    text: Abel  
    code: Abel Mono
  feature:
    tabs: true
  logo: 'assets/images/logo-pdvinfo-300.png'
  palette:
    primary: 'orange'
    accent: 'yellow'

extra_css:
    - css/extra.css    